logging:
  loglevel: debug

init_spark:
  session_conf:
    app_name: 'Ecommerce Generating Samples'
    local: True
    worker_count: 1
    worker_cpu: 2
    server_count: 1
    server_cpu: 2
    batch_size: 256
    worker_memory: '4G'
    server_memory: '4G'
    coordinator_memory: '2G'
  extended_conf:
    spark.network.timeout: '500'
    spark.ui.showConsoleProgress: 'true'
    spark.kubernetes.executor.deleteOnTermination: 'true'
    spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'
  pyzip:
    cwd_path: '/saas/MetaSpore/'

load_dataset: 
  user_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_user.parquet
  item_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_item.parquet
  interaction_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_interaction.parquet
  fmt: parquet

join_dataset:
  join_on: 
    user_key: user_id
    item_key: item_id
    timestamp: timestamp
  user_bhv_seq:
    max_len: 10
  negative_sample:
    sample_ratio: 3

gen_feature:
  reserve_only_cate_cols: True

gen_sample:
  - model_type: ctr_nn
    split_test: 0.15
    shuffle: True
    fmt: parquet
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/nn/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/nn/test.parquet

  - model_type: ctr_gbm
    split_test: 0.15
    use_shuffle: True
    fmt: parquet
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/gbm/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/gbm/test.parquet

  - model_type: match_nn
    split_test: 0.15
    shuffle: True
    fmt: parquet
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/nn/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/nn/test.parquet
    item_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/nn/item.parquet

  - model_type: match_icf
    split_test: 0.15
    shuffle: True
    fmt: parquet
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/icf/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/icf/test.parquet
 
dump_feature:
  mongodb:
    uri: mongodb://localhost:27017/
    database: jpa
    write_mode: overwrite
    index_fields: []
    index_unique: False
  tables:
    - feature_column: 
        - user_id
      mongo_collection: amazonfashion_user_feature
    - feature_column: 
        - item_id
        - category
      mongo_collection: amazonfashion_item_feature
    - feature_column: 
        - item_id
        - category
        - title
        - description
        - image
        - url
        - price
      mongo_collection: amazonfashion_item_summary
