## spark session
spark:
  app_name: 'Ecommerce Generating Samples'
  local: True
  worker_count: 1
  worker_cpu: 2
  server_count: 1
  server_cpu: 2
  batch_size: 256
  worker_memory: '4G'
  server_memory: '4G'
  coordinator_memory: '2G'

## dataset
dataset: 
  user_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_user.parquet
  item_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_item.parquet
  interaction_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_interaction.parquet


  