init_spark:
  session_conf:
    app_name: 'Ecommerce Generating Samples'
    local: True
    worker_count: 1
    worker_cpu: 2
    server_count: 1
    server_cpu: 2
    batch_size: 256
    worker_memory: '4G'
    server_memory: '4G'
    coordinator_memory: '2G'
  extended_conf:
    spark.network.timeout: '500'
    spark.ui.showConsoleProgress: 'true'
    spark.kubernetes.executor.deleteOnTermination: 'true'
  pyzip:
    cwd_path: '/saas/MetaSpore/'

load_dataset: 
  user_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_user.parquet
  item_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_item.parquet
  interaction_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/dataset/amazon_fashion_interaction.parquet
  fmt: parquet

join_sample:
  user_bhv_seq:
    - bhv_seq: user_bhv_item_seq
      by: item_id
    - bhv_seq: user_bhv_cate_seq
      by: category
  negative_sample:
    sample_ratio: 3
  join_on: 
    user_key: user_id
    item_key: item_id
    timestamp: timestamp
  reserve_only_cate_cols: True
  
gen_samples:
  - model_type: ctr_nn
    split_test: 0.15
    shuffle: True
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/nn/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/nn/test.parquet

  - model_type: ctr_gbm
    split_test: 0.15
    use_shuffle: True
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/gbm/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/ctr/gbm/test.parquet

  - model_type: match_nn
    split_test: 0.15
    shuffle: True
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/nn/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/nn/test.parquet

  - model_type: match_icf
    split_test: 0.15
    shuffle: True
    train_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/icf/train.parquet
    test_path: s3://dmetasoul-bucket/sass/ecommerce/amazonfashion/match/icf/test.parquet

