apiVersion: v1
kind: ServiceAccount
metadata:
  name: metaspore-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metaspore-role
rules:
- apiGroups: ["", "apps", "extensions", "metaspore.metaspore.com", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metaspore-role-binding
subjects:
- kind: ServiceAccount
  name: metaspore-account
roleRef:
  kind: Role
  name: metaspore-role
  apiGroup: rbac.authorization.k8s.io