apiVersion: metaspore/v1
kind: Trainingjob
metadata:
  name: Popular
  category: Match/Popular

spec:
  logging:
    loglevel: debug
  
  spark:
    session_confs:
      app_name: Popular Pipeline Demo
      local: false
      worker_count: 2
      worker_cpu: 4
      server_count: 2
      server_cpu: 4
      batch_size: 128
      worker_memory: '4G'
      server_memory: '4G'
      coordinator_memory: '4G'
      
    extended_confs:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'
            
  dataset:
    train_path: s3://dmetasoul-bucket/demo/movielens/ml-1m/popular_ratings.parquet
    user_id_column: user_id
    item_id_column: movie_id
    label_column: label
    label_value: '1'
        
  traning: 
    recall_nums: 200
    group_nums: 10
    

  mongodb:
    uri: mongodb://172.31.37.47:27017/
    database: jpa
    collection: saas_icf
    write_mode: overwrite
    index_fields: []
    index_unique: False
    
  spark_stop:
  